### ISSUE TITLE
promise searchRecords gets rejected.

### ISSUE THREAD

**Issue by plusgut** [gesundheitscloud/hc-sdk-js#41]
When calling the searchRecords, it gets rejected with the message "zkit_sdk is not defined", at the ZeroKitAdapter.decrypt function. 
The issue is, that at the execution-time of searchRecords() the async loading of zkit is in pending state in not yet finished. searchRecords should add itself to the queue, like in the ZeroKitAdapter.getLoginForm does, and make the function asynchronous.

The current implementation assumes that the loginForm is always called before searchRecords, even when an existing session is present. It at least should reject the call with a errormessage like "searchRecords can't be used before an login"

**Comment by Glumli** [comment]
https://github.com/gesundheitscloud/hc-sdk-js/pull/50
