### ISSUE TITLE
searchRecords contains invalid documents

### ISSUE THREAD

**Issue by plusgut** [gesundheitscloud/hc-sdk-js#42]
searchRecords contains invalid documents. When resolving all records, 80% of downloadRecord is successful, but some of them return this response:
```
<Error><Code>BlobNotFound</Code><Message>The specified blob does not exist.
RequestId:1ac3ce1f-001e-001b-4512-40341f000000
Time:2017-10-08T08:48:52.6512166Z</Message></Error>
```

**Comment by Glumli** [comment]
There has been big changes in the sdk. As we don't support downloadRecord anymore I close the Issue.
